import type { Metadata } from 'next';
import '@/assets/styles/global.css';
import Navbar from '@/components/navbar/navbar.component';
import Footer from '@/components/footer/footer.component';
import AuthProvider from '@/components/auth-provider/auth-provider.component';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { GlobalProvider } from '@/context/global.context';

export const metadata: Metadata = {
  title: 'LordEver | Sample booking app',
  description: 'Generated by create next app',
  keywords: 'rental, find rentals, find properties',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
      <AuthProvider>
        <html lang="en" style={{ height: '100%' }}>
          <body
            style={{
              display: 'flex',
              flexDirection: 'column',
              minHeight: '100%',
              margin: 0,
            }}
          >
            <Navbar />
            <main className="bg-blue-50" style={{ flexGrow: 1 }}>
              {children}
            </main>
            <Footer />
            <ToastContainer />
          </body>
        </html>
      </AuthProvider>
    </GlobalProvider>
  );
}
