import type {Metadata} from "next";
import '@/assets/styles/global.css';
import Navbar from "@/components/navbar/navbar.component";

export const metadata: Metadata = {
    title: "LordEver | Sample booking app",
    description: "Generated by create next app",
    keywords: 'rental, find rentals, find properties'
};

export default function MainLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <main>{children}</main>
            </body>
        </html>
    );
}
