import type {Metadata} from "next";
import '@/assets/styles/global.css';
import Navbar from "@/components/navbar/navbar.component";
import Footer from "@/components/footer/footer.component";
import AuthProvider from "@/components/auth-provider/auth-provider.component";

export const metadata: Metadata = {
    title: "LordEver | Sample booking app",
    description: "Generated by create next app",
    keywords: 'rental, find rentals, find properties'
};

export default function MainLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="en">
                <body>
                    <Navbar />
                    <main>{children}</main>
                    <Footer />
                </body>
            </html>
        </AuthProvider>
    );
}
